### ISSUE TITLE
Feature Request:  Disable QuickLinks

### ISSUE THREAD

**Issue by bjvogt** [uweb/uw_wp_theme#12]
Thanks for adding the ability to set a custom menu for QuickLinks!  

Would it be possible to enable/disable QuickLinks via the theme panel?  

Thanks!

**Comment by lcaple** [comment]
In the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0) we added an option to disable Quicklinks. You can fix the checkbox in the Theme Panel options page.

Enjoy 😃
