### ISSUE TITLE
megamenu.js 404 error

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#13]
Hi,

Installed the theme but the megamenu script does not load. Looks like a path issue with a duplicate js folder. Wondering if you can replicate this and confirm this bug?

![image](https://user-images.githubusercontent.com/2615272/137364233-bc525c1f-4efa-4aca-9712-260d31c2a3f9.png)

Thanks,

Jasper Bleijs
Department of Global Health | University of Washington

**Comment by lcaple** [comment]
Alright @jbleys I've made a bugfix which should address the issue. Just pull down the latest on the master branch.

**Comment by jbleys** [comment]
I updated the theme but it looks like the issue persists.
