### ISSUE TITLE
Feature Request:  Footer menu as a WP Menu Location

### ISSUE THREAD

**Issue by bjvogt** [uweb/uw_wp_theme#15]
Similar to how the purple bar audience menu has been crafted.  Thanks!

**Comment by lcaple** [comment]
You'll be happy to know, we already have a footer mega menu in our roadmap! TBD on when we can get it added.

**Comment by lcaple** [comment]
We added this feature in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
