### ISSUE TITLE
Mega Menu nesting headings under headings

### ISSUE THREAD

**Issue by togneter** [uweb/uw_wp_theme#16]
Hi. I am playing with the Mega Menu on my dev site and found that if I have a navigation item with no sub items, the menu doesn't  follow the hierarchy of the navigation as defined in the menu building tool, but treats the next item as a sub item, even if both items are set at the same level.

So, in the menu builder under my Admissions main nav item, I have:

**Find a Program**
**Apply Now**
--Undertanding the Application Process

But it is rendering as:
**Find a Program**
--**Apply Now**
----Undertanding the Application Process

As seen on the site...
<img width="488" alt="Screen Shot 2021-11-09 at 5 34 02 PM" src="https://user-images.githubusercontent.com/61991326/141034884-da5468cb-1fab-4ae5-8b66-9b3187bfccfe.png">
<img width="265" alt="Screen Shot 2021-11-09 at 5 32 08 PM" src="https://user-images.githubusercontent.com/61991326/141034887-1ccdc790-37b6-422b-8876-923869b5fc63.png">

The way around this is to add the 'nav-group' CSS to the top item, which is fine, but isn't particularly intuitive.

Can you update the documentation to reflect this? Took me a while to sort out.

Also, is there a way to have the Mega Menu render according to the hierarchy automatically? I think that would be the expected behavior for most users.

Thanks!

**Comment by lcaple** [comment]
We got this bug fixed in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0

**Comment by togneter** [comment]
Thank you!
