### ISSUE TITLE
Tabs "tour" spacing issue on mobile

### ISSUE THREAD

**Issue by togneter** [uweb/uw_wp_theme#17]
Hi! I was trying out the Tabs feature for one of our pages and tried it in the "tour" configuration. It looks great on my computer, but on mobile, the spacing is all wonky in portrait. It looks fine in landscape. There might just not be enough screen territory to do the tour layout on mobile, honestly.

See below:
![IMG_D77183D32C8C-1](https://user-images.githubusercontent.com/61991326/141510558-ac49a996-2ce2-4745-8594-57297d028728.jpeg)

Thanks!

**Comment by togneter** [comment]
Hello! Just following up to see if this is an issue of concern or just something we have to deal with?

Thank you!

**Comment by lcaple** [comment]
Hi Eric. Thanks for catching and reporting this. We've added it to our bug list and will hopefully get it out on our next update to the theme.

**Comment by lcaple** [comment]
We _finally_ have a new mobile solution for Tours in the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0). They will now output similar to mobile Tabs.

Thanks for reporting this!
