### ISSUE TITLE
Sidebar menu disappears with widgets

### ISSUE THREAD

**Issue by levineaj** [uweb/uw_wp_theme#18]
Sidebar menu disappears if you remove all sidebar widgets.

Currently running a fresh install of Wordpress. Installed and activated uw_wp_theme. Installed and activated Classic Editor and Classic Widgets plugins. Added a parent page and sub page to site and the sidebar menu displays properly. When I remove all widgets from the website the sidebar menu disappears. Adding just any widget to the website brings the sidebar menu back.

If this is not an issue and something the theme is supposed to do please let me know.

Thanks for looking into this.

**Comment by lcaple** [comment]
We got this bug fixed in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
