### ISSUE TITLE
Mobile Menu button appears at bottom of UW Alert

### ISSUE THREAD

**Issue by tjsuw** [uweb/uw_wp_theme#19]
When a UW Alert banner is active, the Menu button is attached to the bottom of the UW Alert, instead of staying in place in the top bar on mobile.

![mobile-nav-button-uw-alert](https://user-images.githubusercontent.com/46610886/147790285-edd9a458-5cc6-48fb-ac32-7a597ca278d3.jpeg)

**Comment by lcaple** [comment]
We got this bug fixed in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
