### ISSUE TITLE
footer nav links protocol

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#20]
Hi,
All the nav links in the footer.php file use the http protocol. Would it not be best practice to use https? Or is there a particular reason not to use https for these?

Thanks,
Jasper Bleijs
Dept of Global Health

**Comment by lcaple** [comment]
This is carry over from the previous theme (built maaaaany years ago), when the washington.edu domain defaulted to http.

Best practice is to match the protocol preferred by the linked site, typically SSL these days. We'll update them accordingly.

**Comment by jbleys** [comment]
> This is carry over from the previous theme (built maaaaany years ago)

I figured as much :) Thanks for addressing it. 
Happy new year!

**Comment by lcaple** [comment]
Updated links in the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0).
