### ISSUE TITLE
'Big Hero' and 'Small Hero' page title repeats

### ISSUE THREAD

**Issue by jh1uw** [uweb/uw_wp_theme#23]
The page title replaces the site title as expected, but it also repeats in the body of the page. The page title should only appear in the header when selecting the 'Big Hero' or 'Small Hero' template in the page editor. We use this feature extensively on site homepages. Example: http://cmsdev.uw.edu/cms/admissions/

**Comment by lcaple** [comment]
This was easy, since I already had the fix coded just not put into the release. There's a test version up on cmsdev now and will be ready for prime time with the next release.

**Comment by lcaple** [comment]
HI @jh1uw, this is now fixed with [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/1.2.0). These updates are on cmsdev and cms.
