### ISSUE TITLE
Menu, Search and Quick Links buttons overlap at breakpoint

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#28]
Hi,

Can you replicate this issue that I noticed at the 767/768 breakpoint?
At 767 the Menu and Quick Links overlap, and
at 768 the Search and the Quick Links overlap.

Images are attached to illustrate the issue.

Thanks,
Jasper Bleijs
Department of Global Health
![766](https://user-images.githubusercontent.com/2615272/151035337-2d3236a3-9eb0-49ba-8a3e-9512696de3cb.JPG)
![767](https://user-images.githubusercontent.com/2615272/151035350-c9d3b429-d405-43a4-b6ee-1d1eb8bd24b2.JPG)
![768](https://user-images.githubusercontent.com/2615272/151035363-acd99f2e-55d4-4516-b20e-52b32450c99d.JPG)
![769](https://user-images.githubusercontent.com/2615272/151035371-dcdd2b1a-fc32-4ab2-963c-b46ada225422.JPG)

**Comment by lcaple** [comment]
Jasper,

Are you experiencing this in the theme out of the box or are you using a child theme/any third party plugins?

Also, can you please let me know what browser, OS, and version of the browser you're using. Thank you!

**Comment by jbleys** [comment]
The issue seems persistent across browsers. I see the same issue in Chrome (Version 97.0.4692.99), Opera (Version:82.0.4227.58), Firefox (96.0.2) and Edge (Version 97.0.1072.69). I'm running Windows 10 Pro 64-bit (build 19043.1466).
The theme is the out-of-the-box child theme and I have three plugins activated: Classic Editor, Classic Widgets and HTTP Authentication.

Thanks

**Comment by lcaple** [comment]
We got this bug fixed in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
