### ISSUE TITLE
Image alignment issue

### ISSUE THREAD

**Issue by eadrapp** [uweb/uw_wp_theme#29]
Hi everyone, I was trying to put some text with a right-aligned image, and every time I would try to do so it would put the image first (still right aligned) and the text below. 
![image](https://user-images.githubusercontent.com/90802184/151260145-32925581-f1ac-4c0b-ad25-1f64b8cd1d69.png)

**Comment by lcaple** [comment]
We got this bug fixed in the latest release: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
