### ISSUE TITLE
Accordion "name" attribute display

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#30]
Hi,

In the `uw-2014` the name attribute of the the Accordion shortcode renders a h3 heading displaying the name above the accordion. This does not appear to be the case in the `uw_wp_theme` theme. I was wondering if this was intentional or not?

Shortcode: https://github.com/uweb/uw_wp_theme#accordion
Example: https://staff.washington.edu/jbleys/wordpress2/accordion/

Thanks,
Jasper Bleijs
Department of Global Health

UW 2014:
![image](https://user-images.githubusercontent.com/2615272/151610094-48e7b492-4de1-426b-9b8c-e8fa16850b61.png)
UW WordPress Theme:
![image](https://user-images.githubusercontent.com/2615272/151610131-71a809e3-a899-4421-836e-9885c8d57cfd.png)

**Comment by lcaple** [comment]
This was intentional, and allows flexibility for folks flexibility with adding content above their accordions. We still give accordions a name for accessibility and identification purposes, but often with the old accordions folks would leave the name blank and add their own titles.
