### ISSUE TITLE
Add submenu items to default dropdown navigation

### ISSUE THREAD

**Issue by jh1uw** [uweb/uw_wp_theme#31]
For the Academics and Research headers, I believe we will need to add a link to the dropdown menu since the main label no longer clicks through to the main page.

Recommended additions - 
Academics at the UW (https://www.washington.edu/about/academics/) under Academics
Research at the UW (https://www.washington.edu/research/) under Research

**Comment by jh1uw** [comment]
Apply already has an Admissions link in the dropdown. Academics and Research are the only dropdowns that need modification.

**Comment by lcaple** [comment]
Great catch! Got this added to the codebase. It will be included the next release.
