### ISSUE TITLE
Search feature issue

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#38]
Hi,

The following issue is also prevalent with the uw-2014 theme.
The issue is observed on the shared web environment (depts.washington.edu, staff.washington.edu.)

The issue: 
The "Current site" search does not resolve to the Site Address of the site, if the site address is a sub directory of the account.

On the depts server the search resolves to the root of the account.
E.g.: The site address is https://depts.washington.edu/edgh/wordpress/
A search on this site resolves to the root of the account https://depts.washington.edu/edgh
We have a redirect in the root so the the search action actually takes you to another website.

On the staff server the search resolves to the server domain.
E.g.: The site address is https://staff.washington.edu/jbleys/wordpress2/
A search on this site resolves to the server domain https://staff.washington.edu

Let me know if you can replicate the issue.

I think the issue traces back to UW.getBaseUrl function in the uw.init.js file of uw-2014 theme.

Thanks,

Jasper Bleijs
Dept of Global Health

**Comment by lcaple** [comment]
This is fixed in the theme, shouldn't have an issue with it in the latest: https://github.com/uweb/uw_wp_theme/releases/tag/2.0.0
