### ISSUE TITLE
Featured image on blog posts showing in header

### ISSUE THREAD

**Issue by whitenc** [uweb/uw_wp_theme#40]
When I set a featured image on a blog post while using the new UW WordPress Theme, it updates the header image to the featured image instead of using the header image I selected through Appearance. 

![image](https://user-images.githubusercontent.com/103532192/163037408-9fed6367-f011-42ec-9b99-6350d64cbb4d.png)

https://cmsdev.uw.edu/cms/federalrelations/wp-admin/post.php?post=97&action=edit

**Comment by lcaple** [comment]
Fixed this in release [1.3.1](https://github.com/uweb/uw_wp_theme/releases/tag/1.3.1)
