### ISSUE TITLE
Safari breadcrumb layout bug

### ISSUE THREAD

**Issue by tjsuw** [uweb/uw_wp_theme#41]
This bug report originally came from @twthorpe .

The breadcrumbs have what appears to be a line height issue in Safari. See screenshots below for reference.

The first screenshot is from Safari.

<img width="572" alt="Screen Shot 2022-05-06 at 7 44 25 PM" src="https://user-images.githubusercontent.com/46610886/167235111-486f7511-482f-4a02-a50b-f2cfbea7e130.png">

The second is from Chrome (Firefox is the same as Safari), where it looks normal.

![Undocumented-student-resources-–-Admissions](https://user-images.githubusercontent.com/46610886/167235125-b76e36bd-c309-4b16-bbf2-9d7f6f0a3883.jpeg)

Interestingly, this seems to be happening in 2014 too:

<img width="743" alt="Screen Shot 2022-05-06 at 7 53 36 PM" src="https://user-images.githubusercontent.com/46610886/167235266-0de02f5e-261e-455c-b357-5a8dc29989e7.png">

So this may actually be a Safari bug but we should be able to fix it so that it works the same across browsers.

Pages for reference: [Undocumented student resources](https://www.washington.edu/admissions/undocumented/) and [Financial Aid](https://www.washington.edu/financialaid/).

**Comment by lcaple** [comment]
This appears to be fixed in the new theme, or is no longer appearing in Safari 15.
