### ISSUE TITLE
Header appears twice on People directory pages

### ISSUE THREAD

**Issue by jh1uw** [uweb/uw_wp_theme#44]
I'm having an issue with the People directory plugin in the new theme. The top portion of the page (purple logo area and white bar site navigation) appear twice on the default people directory page and each of the profile pages
![Screen Shot 2022-08-15 at 9 38 54 AM](https://user-images.githubusercontent.com/16327063/184677287-76676c86-5aa5-4661-a4b8-f1cdd82344a5.png)
.

**Comment by lcaple** [comment]
Hi Jeff,

This is related to People Directory plugin, which hasn't been updated or tested in the new theme. I'll look it to the issue on that codebase.

**Comment by lcaple** [comment]
I have a fix for this. Coordinate with me when it should be rolled out for this site.
