### ISSUE TITLE
Trumba shortcode request: URL Parameter

### ISSUE THREAD

**Issue by bjvogt** [uweb/uw_wp_theme#45]
As we continue to do more with trumba, we find ourselves relying on the URL parameter more and more often.  

This parameter is not a uniform resource locater.  Rather, it's a way of passing arguments to trumba spuds and is quite robust with almost two dozen different trumba controls exposed.  [See [https://www.trumba.com/help/api/urlparameters.aspx](https://www.trumba.com/help/api/urlparameters.aspx)]

However, there's no [trumba] shortcode parameter currently in place to invoke this powerful trumba feature.  

I've begun exploring a very rudimentary short code implementation via our child theme, and it's functional enough I thought it might be useful to others using the theme.  The idea is to replace trumba javascript calls with a shortcode, thus: 

```
<script type="text/javascript" src="https://www.trumba.com/scripts/spuds.js"></script>
<script type="text/javascript">    
$Trumba.addSpud({
    webName: "sea_be",
    spudType : "upcoming" ,
    url : { filterview : "CM" } ,    
    teaserBase : "https://cm.be.uw.edu/events-meetings/"
});
```

becomes: 

`[get_trumba url='filterview : "CM"' spud="upcoming" base="https://cm.be.uw.edu/events-meetings/"]`

```
// Shortcode from functions.php of child theme
function getTrumba ($atts = array()) {

    // set up default parameters so [get_trumba] with no params shows main calendar view
    extract(shortcode_atts(array(
        'name' => 'sea_be',
        'spud' => 'main',
        'url' => '',
        'base' => 'https://be.uw.edu/news-events/cbe-event-calendar/'
    ), $atts));
    
    $trumbaHTML = '<script type="text/javascript" src="https://www.trumba.com/scripts/spuds.js"></script>';
    $trumbaHTML .= '<script type="text/javascript">
    $Trumba.addSpud({
        webName: "' . $name . '",
        spudType : "' . $spud . '" ,
        url : { ' . $url . '} ,
        teaserBase : "' . $base . '" 
    });
    </script>';

    return $trumbaHTML;
}
add_shortcode('get_trumba', 'getTrumba');
```

**Comment by lcaple** [comment]
Hi! We've added the url parameter to the trumba shortcode for the next release. Thanks for the suggestion.

**Comment by bjvogt** [comment]
Love it when I can retire child theme code in favor of W theme functionality.  Thanks very much Lauren!!

Cheers,
Brian Vogt
Web Developer
College of Built Environments
Pronouns: he/him/his
