### ISSUE TITLE
bad link in whitebar menu

### ISSUE THREAD

**Issue by SalsaT** [uweb/uw_wp_theme#46]
In the whitebar.php file there is a link in the Academics dropdown menu that points to https://helpcenter.uw.edu/registration-resources/. The helpcenter.uw.edu website was deprecated over a year ago. 

The link should instead point to: https://registrar.washington.edu/registration/resources/.

**Comment by lcaple** [comment]
Thanks for flagging this! I am going to update the menu to match the UW Homepage, which currently links to https://registrar.washington.edu/registration/

This will be out in our next release.
