### ISSUE TITLE
Banner message issue

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#47]
Hi,

The new banner message field does not properly sanitize html input.

![banner_message_input](https://user-images.githubusercontent.com/2615272/200674868-b7e08027-c914-49f6-92cd-04e0dc84a3a3.JPG)

Thanks for all your work,

Jasper Bleijs
Dept of Global Health

**Comment by lcaple** [comment]
Just got this fixed in the latest update. Thanks!

**Comment by jbleys** [comment]
Hi,
Sorry to reopen this, but there still seems to be an issue with the output. Spaces on either side of an html element are being removed in the rendered output. The input field works fine now.

input:
![2 0 1-banner_message_input](https://user-images.githubusercontent.com/2615272/200988664-cb357c94-f103-4622-b78d-6c43ea1c0886.JPG)

output:
![2 0 1-banner_message_output](https://user-images.githubusercontent.com/2615272/200988699-7b0681e9-af00-417b-9e8c-448ee4724349.JPG)

Thanks,
Jasper

**Comment by jbleys** [comment]
An additional example about the banner message rendering issues.

input:
![2 0 1-banner_message_input_1](https://user-images.githubusercontent.com/2615272/201742905-5438f293-a61e-4e3f-b213-a4cd1ef1c8c8.JPG)

output:
![2 0 1-banner_message_output_1](https://user-images.githubusercontent.com/2615272/201742957-09dd4512-5f4a-4344-828d-6f2543a0aa8d.JPG)

To inspect the source code, see:  https://depts.washington.edu/uwhivishub/

Thanks,
Jasper

**Comment by jbleys** [comment]
Can we also get the options for the original bootstrap alert colors back, that were in the 2.0.0 release?

**Comment by tjsuw** [comment]
Hi Jasper, the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/2.1.1) should resolve this issue for you.
