### ISSUE TITLE
Footer content alignment

### ISSUE THREAD

**Issue by jbleys** [uweb/uw_wp_theme#48]
Hi,

The alignment of the social links vs the footer links seems off to me. This is more noticable when the number of items in the footer menu is reduced.

![footer_menu_alignment](https://user-images.githubusercontent.com/2615272/200962121-1f878259-9038-4604-92ea-395213131c6c.JPG)

Thanks,

Jasper Bleijs
Dept of Global Health

**Comment by tjsuw** [comment]
This was fixed in the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/2.1.1).
