### ISSUE TITLE
Attachment Page author vs image credit

### ISSUE THREAD

**Issue by bjvogt** [uweb/uw_wp_theme#49]
On an attachment page, the wordpress user is credited, like a blog post byline.  Would it be possible to instead reference the image credit and url fields from the media library metadata?  

Thanks!
b

**Comment by bjvogt** [comment]
an option to toggle sidebar visibility on this template would also be amazing.

**Comment by lcaple** [comment]
We got a lot of requests to remove author information on attachment pages, [so that's gone now in the 2.2.0 release](https://github.com/uweb/uw_wp_theme/releases/tag/2.2.0). Removing the bug tag and flagging this for your other two requests.

**Comment by lcaple** [comment]
We've added image credit to the attachment pages [in the latest release](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0).
