### ISSUE TITLE
Nested shortcodes issue

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#51]
Hi,

I tried nesting an accordion inside a tab and it looks like the closing `</button>` element of the accordion is not rendering correctly.

my content input:
![2 0 1_nested_shortcode-input](https://user-images.githubusercontent.com/47229745/202025184-e0ce540d-6118-48bf-9c1e-ab2acecd1cc2.JPG)

rendered output:
![2 0 1_nested_shortcode-rendered](https://user-images.githubusercontent.com/47229745/202025242-56cd68ba-e99c-493c-8b48-982d56416ed3.JPG)

Source output:
![2 0 1_nested_shortcode-output](https://user-images.githubusercontent.com/47229745/202025287-4d77bb77-2276-4dba-990f-fbace7007b48.JPG)

Thanks,
Jasper Bleijs
Dept of Global Health

**Comment by tjsuw** [comment]
This was fixed in the [latest release](https://github.com/uweb/uw_wp_theme/releases/tag/2.1.1).
