### ISSUE TITLE
Feature request: uw_card image and title link

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#53]
Hi,

I've received a few request for the cards to have the image (specifically for styles "inset" and "image-top") and the card title also link out. Currently only the button links out.

See these pages as an example, where I customized the card styles for this specific need.
[https://depts.washington.edu/uwbirch/people/](https://depts.washington.edu/uwbirch/people/)
[https://depts.washington.edu/globalhealthjustice/](https://depts.washington.edu/globalhealthjustice/)

On the user side, I could see this work as some added attributes for the `[uw_card]` shortcode. E.g.:  `linked_image=true` and `linked_title=true`

Thanks for taking this in consideration.

Jasper Bleijs
Dept of Global Health

**Comment by lcaple** [comment]
We'll consider this for a future release. In the meantime, I recommend using the [Stretched Link ](https://getbootstrap.com/docs/4.6/utilities/stretched-link/)option with card HTML or in a child theme.

**Comment by dghweb** [comment]
A "stretched link" option as a card attribute would suffice as well. Thanks for pointing out that bootstrap class.

**Comment by lcaple** [comment]
We added the stretch link option[ in the latest release](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0).
