### ISSUE TITLE
uw_card titletag values are all displayed the same

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#54]
Hi,

The `[uw_card]` `titletag` attribute options h2, h3 and h4  all use the same style rule, and all display identical.
I'd assume that h3 and h4 would display with a smaller font-size.

![image](https://user-images.githubusercontent.com/47229745/205845191-8618f5e2-f62d-4a5b-ab47-dadbee5a2c62.png)

Thanks,
Jasper
Dept of Global Health

**Comment by lcaple** [comment]
Hi Jasper, this is the intended functionality. We would like the style of the cards to be consistent, but the information hierarchy to make sense for accessibility purposes.
