### ISSUE TITLE
The author name is appearing with sub-page list shortcode

### ISSUE THREAD

**Issue by jeanem** [uweb/uw_wp_theme#55]
When using the Sub-Page List short-code, the page author's name is displaying in the sub-page lists. 

The author name disappears on the sub-page list when "Show bylines on single posts and archives" in the UW theme settings is unchecked, but we need to keep that option active so we can display the date on blog posts. Should those blog post settings effect a page display?

- Shortcode: [subpage-list link="More information here" tilebox="false" ]
- Screenshots attached (including one with the tilebox set to true)
- Tested on uw_wp_theme 2.1.1, WP version 6.1.1, no child theme included

Let me know if you have any questions or if this is just a configuration that I have set up incorrectly.

Thanks!

![Screenshot 2022-12-06 at 09-27-28 Sub-page list test](https://user-images.githubusercontent.com/7515092/206049993-3ac3943d-6ece-40c8-9e35-538a0778a2da.png)
![Screenshot 2022-12-06 at 09-21-17 UW Theme Settings ‹ No child theme — WordPress](https://user-images.githubusercontent.com/7515092/206049997-4e5b0d7f-1ca1-4bc7-9053-1fe8e20b9303.png)
![Screenshot 2022-12-06 at 09-20-29 Sub-page list test](https://user-images.githubusercontent.com/7515092/206049998-184328af-26e8-4248-a161-4fb63ea4e963.png)

**Comment by lcaple** [comment]
[This bug is fixed in our 2.2.0 release](https://github.com/uweb/uw_wp_theme/releases/tag/2.2.0).
