### ISSUE TITLE
Media/caption/custom url?

### ISSUE THREAD

**Issue by bjvogt** [uweb/uw_wp_theme#56]
I'm experiencing a problem when placing media that should link to a custom url (not attachment page or file) and also displaying Description.  

Linking to the specified custom url does not happen.  Instead, a blank lightbox appears with Description but no image.

Removing the [caption] shortcode resolves at the expense of caption styling.  

Anyone else encounter this?

**Comment by lcaple** [comment]
This is a bug we've flagged and we're working on fixing in our next update.

**Comment by lcaple** [comment]
This is fixed [in the latest release](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0).
