### ISSUE TITLE
Site-wide Banner Notification

### ISSUE THREAD

**Issue by unrulybeep** [uweb/uw_wp_theme#57]
Hello! I see that there is a [Site-wide Notification Banner option](https://github.com/uweb/uw_wp_theme#site-wide-notification-banner). I don't see this in the location stated.
<img width="1272" alt="Screen Shot 2022-12-18 at 00 53 57" src="https://user-images.githubusercontent.com/4535231/208289501-58d62e13-0c05-4d79-8add-aca227fb76ad.png">

I am using a "Child Theme," so perhaps I missed adding something to activate this feature?

Also, the description says it should be a "short-lived announcement". The site I'm building is archival and hosted by the library. It is for a professor's research project, and is being created as a supplement to future scholars who may want to pursue a similar project or who may look for more information about this particular research project. The banner is going to have a message along the lines of, "This is an archival site that will not be updated in the future." Would it be OK to use the site-wide notification banner in this way? If not, do you have a suggestion on another way to convey this message to visitors?

Thank you for your time!

**Comment by lcaple** [comment]
It looks like you're using an older version of the theme. [Please update uw_wp_theme to the latest version](https://github.com/uweb/uw_wp_theme/releases/tag/2.1.1).

You can use the feature however you see fit. Our description is merely a suggestion on how best to use it. If you think that works for your needs, feel free to use the banner.

**Comment by unrulybeep** [comment]
Rookie mistake. Thank you for the gentle reminder to always check for updates first.

I did update the theme, and I see the banner on my site. However, I still don't see the option to edit it under Appearance.
<img width="1262" alt="Screen Shot 2022-12-24 at 00 54 37" src="https://user-images.githubusercontent.com/4535231/209428516-89374ec4-2f72-49a8-9ce9-a22c962c4826.png">

**Comment by lcaple** [comment]
Not sure what would cause this issue. There may be a conflict in your child theme if it isn't showing up. If you track down an issue, please reach out and let us know.

Also that banner you're seeing is the [UW Alert banner](https://www.washington.edu/safety/alert/) for UW campus-wide safety and emergency information. This is separate from the site notification banner.
