### ISSUE TITLE
Angled bar missing on purple "no-image" cards.

### ISSUE THREAD

**Issue by togneter** [uweb/uw_wp_theme#59]
The title pretty much sums it up. The white and gold cards have the angled underline to match the title text color (purple). The purple card does not show the line (I'm assuming it's there but that it's purple and so not visible on the purple background).

Image below...

<img width="798" alt="Screenshot 2023-01-30 at 4 05 37 PM" src="https://user-images.githubusercontent.com/61991326/215880751-2da4d687-6fb4-44cb-8155-40c88929e731.png">

**Comment by lcaple** [comment]
This is fixed [in the latest relase](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0).
