### ISSUE TITLE
Accordion Name

### ISSUE THREAD

**Issue by SalsaT** [uweb/uw_wp_theme#61]
I noticed that when the Accordion name begins with a number it keeps the accordion sections from opening.
[accordion name="2022 Updates"] The sections highlight on hover but do not open.
[accordion name="Updates for 2022"] The sections open as expected.

**Comment by lcaple** [comment]
This is fixed in [the latest release ](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0)

[Please checkout out the ReadMe](https://github.com/uweb/uw_wp_theme#accordion) for important information about accordion updates and guidance.
