### ISSUE TITLE
Megamenu multi-column dropdown border missing

### ISSUE THREAD

**Issue by levineaj** [uweb/uw_wp_theme#62]
Missing bottom border in the first list item on the second column of mega menu dropdown.
 
It looks like the following css (located in the parent theme bootstrap.css stylesheet) removes any bottom borders from one column nav dropdowns at the very last nav item. However, this also removes the bottom border from multi column nav dropdowns.
 
.navbar.secondary-nav .navbar-nav .nav-item.dropdown .dropdown-menu.multi-column li:last-of-type a,.navbar.white-bar .navbar-nav .nav-item.dropdown .dropdown-menu.multi-column li:last-of-type a {
    /* border-bottom:0 none; */
}
![Screenshot 2023-04-18 at 2 01 05 PM](https://user-images.githubusercontent.com/12614389/233699448-78df3a05-1a9d-487c-89a1-47a9c77abf45.png)

**Comment by lcaple** [comment]
This looks like an issue with the `li:last-of-type` marker. I am only able to reproduce it when links are nested under others without a heading.

Are you creating two columns by nesting other links under PGRN?

Our Mega Menus were designed to be used with headings to create columns, which is important for content hierarchy for things like screen readers to navigate the content. I recommend if you can creating headings for your columns and grouping your menu links under them to make a better menu user experience/accessibility for folks and avoid this underline issue. [More info on that here in the ReadMe](https://github.com/uweb/uw_wp_theme#mega-menu-columns).

**Comment by levineaj** [comment]
I’m creating 2 columns without headings. Since there are more than 8 items in some of the main nav dropdowns the new theme does not break long lists into 2 columns like the old theme. Instead, the list of items extends far down the page. Maybe that is a separate bug? Any lists longer than say 8 items should be broken into 2 columns? I can show you examples if needed.

Thanks for looking into.

Alex Levine
Web Computing Specialist
University of Washington School of Pharmacy
UW Box 357631, Seattle, WA 98195
o: 206-616-9905 m: 206-920-2809
***@***.******@***.***> sop.washington.edu<https://sop.washington.edu/>

From: Lauren Caple ***@***.***>
Reply-To: uweb/uw_wp_theme ***@***.***>
Date: Friday, April 21, 2023 at 11:11 AM
To: uweb/uw_wp_theme ***@***.***>
Cc: Alex Levine ***@***.***>, Author ***@***.***>
Subject: Re: [uweb/uw_wp_theme] Megamenu multi-column dropdown border missing (Issue #62)


This looks like an issue with the li:last-of-type marker. I am only able to reproduce it when links are nested under others without a heading.

Are you creating two columns by nesting other links under PGRN?

Our Mega Menus were designed to be used with headings to create columns, which is important for content hierarchy for things like screen readers to navigate the content. I recommend if you can creating headings for your columns and grouping your menu links under them to make a better menu user experience/accessibility for folks and avoid this underline issue. More info on that here in the ReadMe<https://urldefense.com/v3/__https:/github.com/uweb/uw_wp_theme*mega-menu-columns__;Iw!!K-Hz7m0Vt54!iB1eYIhSfFu05oDogQi2QKv7mzhh0HSqszRVec-RtihqvKmwG1B0jjcUhmUH9s6HvEimxiXOdcJRqE9GfWLhxFtP$>.

**Comment by lcaple** [comment]
We can add automatic multi-column menus as a feature request for future updates on the theme.

**Comment by levineaj** [comment]
That would be great! Thank you.

Alex
________________________________

**Comment by lcaple** [comment]
We've added a wrapping option for the classic menu that addresses this issue. 

We still recommend only using the Mega Menu if you've leveraging the header features for the menu. Otherwise, the Classic menu can now accommodate longer menus with it's auto-wrap feature.
