### ISSUE TITLE
Feature enhancement: link styled modal

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#66]
Hi, I have another feature request.  A [modal](https://www.washington.edu/docs/shortcode-cookbook/modals/) that is styled as a standard inline link.

Thanks,
Jasper Bleijs
Dept. of Global Health

**Comment by lcaple** [comment]
Hi Jasper,

Modals are the type of on-page action that it's recommended, from an accessibility and usability standpoint, to use a button to convey an action that isn't taking you off a page (which is what links are intended to do). With that, this likely isn't a feature we'll add to the theme. You're welcome to add it to a child theme, though!

[Reference](https://www.w3.org/WAI/ARIA/apg/patterns/button/).
