### ISSUE TITLE
Bug: can't use more than 1 vertical Tabs on a page

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#69]
Hi,

The vertical tabs (tour="true") are not assigned a unique id value.  When a second vertical Tabs structure is added, its section navigation links trigger the panes of the first vertical Tabs structure on the page.

Observed in Version: 2.3.1

Thanks,
Jasper Bleijs
Dept. of Global Health

**Comment by lcaple** [comment]
This is fixed in [the latest release ](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0)
