### ISSUE TITLE
Bug: multiple modals inside tabs

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#72]
Hi,

I noticed an issue with the modals shortcode not rendering correct id's (and data-targets on the associated button) when multiple modal shortcodes are inside a tab shortcode structure:
<pre>
[uw_tabs]
[tabs_section title="Tab title"]
    [uw_modal title="Hello" width="default" color="gold" button="Hello" position="center"]Hello[/uw_modal]
    [uw_modal title="World" width="default" color="gold" button="World" position="center"]World[/uw_modal]
[/tabs_section]
[/uw_tabs]
</pre>
The attached image has screenshot showing the rendering of two modals in the regular entry-content (marked green), and the same modals nested inside a tab-pane. You can see where the issues are (marked red).
![image](https://github.com/uweb/uw_wp_theme/assets/47229745/bb2793ff-c0ca-4e5d-b6e4-cab445e4b59c)

Thanks,
Jasper Bleijs
Dept. of Global Health

**Comment by dghweb** [comment]
Quick follow-up: 
When the modals inside the tab are wrapped in `<p></p>` tags the issue gets resolved.

**Comment by lcaple** [comment]
We believe this this is fixed in [the latest release ](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0) with the addition of unique IDs in all shortcodes.

Let us know if this issue persists for you by reopening this issues.
