### ISSUE TITLE
Link in header is clearing floats

### ISSUE THREAD

**Issue by levineaj** [uweb/uw_wp_theme#73]
When a header is linked it is moved down to clear a floating element instead of moving to the side of the element.

Example: 
```
<img class="alignleft" src="/" alt="/" />
<h2><a href="/">text</a></h2>
```

Possible fix:
h1,h2,h3,h4,h5,h6 {
    clear: none;
}

**Comment by lcaple** [comment]
This is fixed in [the latest release ](https://github.com/uweb/uw_wp_theme/releases/tag/3.0.0)
