### ISSUE TITLE
[BUG] issue with radio/checkbox bug fix in update 3.0.1 --> Conflict with Formidable Forms plugin

### ISSUE THREAD

**Issue by dghweb** [uweb/uw_wp_theme#76]
## Describe the bug

The 3.0.1 version injects unwanted html elements to our Formidable form. See the attached image to see the span element that gets injected. This never happened with previous versions of the UW WordPress theme.

I rolled the uw_wp_theme parent theme back to version 3.0.0 to resolve the issue. But as it stands I can't update the parent theme on sites that use Formidable Forms.

## Steps to reproduce

You can review the issue on this page on my sandbox site: https://staff.washington.edu/jbleys/apply/
This page has the parent theme activated to show that it's not an issue with a child-theme

## Possible Solution

Can you please review the 3.0.1 update with regards to this issue?

## Screenshots / Video

![image](https://github.com/uweb/uw_wp_theme/assets/47229745/ef89ef87-da8e-40a9-8482-10e0abf181ad)

Kind regards,

Jasper Bleijs
Dept. of Global Health

**Comment by lcaple** [comment]
This should be resolved in the latest [3.1 release](https://github.com/uweb/uw_wp_theme/releases/tag/3.1). We removed all .js modifications and are now using pure CSS.
